[package]
name = "main"
version = "0.1.0"
edition = "2018"

[dependencies]
fastly = "0.9.0"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "main"
path = "src/lib.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1 