[build]
target = "wasm32-wasip1"

[target.wasm32-wasip1]
rustflags = [
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--initial-memory=2097152",
    "-C", "link-arg=--max-memory=2097152",
    "-C", "link-arg=--stack-first",
    "-C", "link-arg=--export-table",
] 